[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[project]
name = "imgread_benchmark"
version = "0.3.2.dev1"
description = "benchmark for read images."
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "Apache-2.0" }
authors = [{ name = "Yasyrev Andrei", email = "a.yasyrev@gmail.com" }]
requires-python = ">=3.12,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "argparsecfg",
    "benchmark_utils",
    "numpy",
    "pillow",
    "requests>=2.32.5",
    "rich",
]

[project.urls]
Homepage = "https://github.com/ayasyrev/imgread_benchmark"

[project.scripts]
imgread_benchmark = "imgread_benchmark.cli:main"

[project.optional-dependencies]
dev = [
    "black",
    "black[jupyter]",
    "coverage[toml]",
    "flake8",
    "isort",
    "mypy",
    "nbmetaclean",
    "nox",
    "pre-commit",
    "ruff",
    "torchvision",
]
test = [
    "pytest",
    "pytest-cov",
]
img_libs = [
    "imageio",
    "jpeg4py",
    "kornia",
    "kornia_rs",
    "opencv-python-headless",
    "scikit-image",
    "ajpegli",
    "imagecodecs",
    "simplejpeg",
    "turbojpeg",
]

[tool.imgread.conda-deps]
packages = [
    "accimage",
    "imread",
]
